version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: test
    ports:
      - "8888:5432"

  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - "5555:8080"